name: deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install mkdocs-material
      - run: mkdocs build --clean
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: ${{ github.repository }}-deploy-${{ github.run_id }}
      - run: aws s3 sync site s3://${{ vars.S3_BUCKET }}/ --delete --only-show-errors
      - run: aws s3 cp site s3://${{ vars.S3_BUCKET }}/ --recursive --exclude "*" --include "*.html" --cache-control "public,max-age=0,s-maxage=31536000,must-revalidate" --metadata-directive REPLACE
      - run: aws s3 cp site s3://${{ vars.S3_BUCKET }}/ --recursive --exclude "*.html" --cache-control "public,max-age=300,s-maxage=31536000" --metadata-directive REPLACE
      - run: aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"

